### ISSUE TITLE
Corrupted launchers

### ISSUE THREAD

**Issue by janekgithubek** [dkondor/cairo-dock-core#14] opened 2024-04-25 09:19 UTC
Hi,

Great work with Wayland support but since commit https://github.com/dkondor/cairo-dock-core/commit/1a685ace16d500fb03a01ae30ddaacb065f226d2 launchers get corrupted in folder ~/.config/cairo-dock/current_theme/launchers/ with this commit I'm getting a folder inside with some icons. With the newest commit my launcher files get corrupted instead of file names I have glyphs in names. Dock is not editable, you can remove activators but on next start they will appear back. 

Environment: Plasma 6 on Wayland

**Comment by dkondor** [comment] 2024-04-25 19:52
Hi,
thank you for reporting! Indeed, I see an issue with storing the path of launchers. I created a possible fix here:
https://github.com/dkondor/cairo-dock-core/tree/fix_icon_path
Could you test it? (either the branch or just by cherry-picking [a3885e9](https://github.com/dkondor/cairo-dock-core/commit/a3885e94035fd276df34fe7654e0447f7f9bcf5d))

**Comment by janekgithubek** [comment] 2024-04-25 21:09
Hi,

Thank you for quick response, it fixed the issue for me. It is expected behavior that every launcher gets modification date from first start of the cairo-dock with the fix?

ps. the subdocks are rendered little lower on wayland than on x11, on wayland the the subdock pointer covers the name of subdock.

**Comment by dkondor** [comment] 2024-04-26 20:00
Hi,

thank you for testing. Since then, I've noticed some issues, so the fix might not be complete, so I'll do some more tests before merging. Regarding the modification date thing, I'm not sure why launchers get updated, but this change should not affect when this happens, so I'll also need to look into it a bit more.

Regarding the subdocks, I strangely haven't noticed this before, but I can confirm now, and probably adding an offset to not cover the label would make sense.

**Comment by dkondor** [comment] 2024-04-28 18:35
Hi,
I did some more testing and merged the fix. Updating the modification date is actually expected, since I recently changed the version number which is stored in the launchers -- so all launchers get updated when it changes.
I'll look into the subdock behavior separately.

**Closed as completed by dkondor** 2024-04-28 18:35 UTC
