### ISSUE TITLE
Crash with HiDPI scale

### ISSUE THREAD

**Issue by ssfdust** [dkondor/cairo-dock-core#7] opened 2023-11-07 10:23 UTC
with any scale factor over 1, the cairo-dock will crash with the following messages:
```
EGL version: 1;5
                                                                                                                                                            
 ============================================================================
        Cairo-Dock version : 3.4.99.alpha1
        Compiled date      : Nov  6 2023 09:02:32
        Built with GTK     : 3.24
        Running with OpenGL: 1
 ============================================================================
                                                                                                                                                            
g_file_test: assertion 'filename != NULL' failed
g_file_test: assertion 'filename != NULL' failed
Gdk-Message: 18:15:59.680: Error 71 (Protocol error) dispatching to Wayland display.

```
the example of `~/.config/kanshi/config`
```
profile {
    output HDMI-A-1 mode 1920x1080 scale 1.1
}
```

**Comment by dkondor** [comment] 2023-11-07 22:02
Hi,
thank you for reporting, I can also reproduce this when using OpenGL, and it seems that the EGL code is not using the correct (scaled) sizes. I will look into this more to see how easy it is to fix.

In the meantime, a workaround that works for me is to disable OpenGL, by using the following command line:
```
cairo-dock -c -L
```
Let me know if this helps in your case as well.

**Comment by ssfdust** [comment] 2023-11-08 01:11
It won't crash any more with OpenGL disabled, thanks. I notice the work is in progress in the egl_scale branch, if the work is done, I am willing to test.

**Comment by dkondor** [comment] 2023-11-09 21:27
Great, thanks. I'm looking into this, but it might be a bigger issue -- it seems that even on X11, rendering is incorrect with OpenGL if the display scale is > 1; so it might take a while before I come up with anything

**Comment by dkondor** [comment] 2023-11-10 22:20
I have a solution in the [egl_scale](https://github.com/dkondor/cairo-dock-core/tree/egl_scale) branch now. Any testing is very welcome :) For correct functioning, you might also need to use [this branch](https://github.com/dkondor/cairo-dock-plug-ins/tree/egl_scale) for the plug-ins (depending on which subdocks you use).

Caveats:
 - Things might still be blurry, since making sure that everything is rendered in high resolution seems to be more complicated. This only fixes the crash and the size / position of elements. I'd be happy to hear any feedback, especially if there is any visible difference compared to rendering with OpenGL disabled.
 - I've only tested with horizontal docks and only one screen.
 - Also didn't test changing the scale factor while the dock is running.

**Comment by ssfdust** [comment] 2023-11-12 02:58
Thank you! After applying the latest patch, Cairo-Dock no longer crashes in OpenGL mode. 
And yes, the enlarged icons appear slightly blurry when I hover the mouse over them. I'm using a 4K monitor with a scale factor of 2, and the icon rendering seems to be fine. So far, I haven't encountered any other issues compared to the non-OpenGL mode.

**Comment by dkondor** [comment] 2023-11-12 19:58
Thank you for testing! I'll leave this issue open and will try to deal with the blurriness eventually

**Comment by ssfdust** [comment] 2023-11-22 11:58
I have updated to the latest git version, it looks much better now, thanks a lot.

**Comment by dkondor** [comment] 2023-11-22 16:25
Thanks for the additional testing! I've made changes in several places that aim to ensure high resolution rendering -- although I'm not sure if this really covers everything.
I'll close this issue as the original problem is solved though.

**Closed as completed by dkondor** 2023-11-22 16:25 UTC
